jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    # --- ESTRATEGIA DE MATRIZ ---
    strategy:
      fail-fast: false # Para que si uno falla, los otros sigan corriendo
      matrix:
        feature_file: [login, logOut, inventory] # Aquí pones los nombres de tus archivos
    # ----------------------------

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Generate BDD Test Files
      run: npm run bdd:generate

    - name: Run Playwright test: ${{ matrix.feature_file }}
      # Usamos -g (grep) para filtrar por el nombre del archivo generado
      run: npx playwright test ${{ matrix.feature_file }}

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        # Le ponemos un nombre único al reporte de cada archivo
        name: report-${{ matrix.feature_file }}
        path: playwright-report/
        retention-days: 30